version: "3.9"

services:
  core:
    build:
      dockerfile: Dockerfile
      context: core
    container_name: core
    privileged: true
    volumes:
      - ./core:/app:ro
      - ./shared:/shared
      - ./models/default:/config
    devices:
      - /dev:/dev